#!/Users/vladimir/anaconda3/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'mrec==0.3.1','console_scripts','mrec_evaluate'
__requires__ = 'mrec==0.3.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('mrec==0.3.1', 'console_scripts', 'mrec_evaluate')()
    )
